# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

  [[main]]
    name = "个人简介"
    url = "#about"
    weight = 10
  [[main]]
    name = "科研项目"
    url = "#funding"
    weight = 20
  [[main]]
    name = "学术论文"
    url = "#featured"
    # identifier = "pub"
    weight = 30
  [[main]]
    name = "科研随笔"
    url = "#posts"
    # parent = "pub"
    weight = 40
  [[main]]
    name = "所在团队"
    url = "#people"
    weight = 50
  [[main]]
    name = "招生信息"
    url = "enrollment/"
    weight = 50
